id = "why-i-blog"

[base]
created_at = "2023-06-29T21:24:00+08:00"
# updated_at = "2026-05-13T20:47:09+08:00"
draft = false
# cover = "" # optional
# title = "Multimodal Machine Learning"
# description = "" # optional

[versions.en]
title = "Why I Blog?"
description = "The first article on this site"

[versions.zh]
title = "为什么我要写博客?"
description = "本站的第一篇文章"
