id = "digital-design-arithmetic-adder"

[base]
created_at = "2023-06-30T11:30:14+08:00"
# updated_at = "2026-05-13T20:47:09+08:00"
draft = false
# cover = "" # optional
# title = "Multimodal Machine Learning"
# description = "" # optional

[versions.zh]
title = "从半加器、全加器到超前进位加法器"
description = "空间换时间的智慧"
