name: Deploy
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: "10"

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: pnpm

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - name: Deploy
        uses: imajeetyadav/rsync-deployer@2.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source_path: dist/
          target_path: /usr/share/nginx/html/blog
          delete_option: true
          print_summary: true
          print_statistics: true
          debug: false
